### ISSUE TITLE
OpenVPN deprecated AMIs

### ISSUE THREAD

**Issue by ghost** [Accenture/adop-aws#15]
Whilst deploying OpenVPN in us-east-1 I had to change AMI for BYOL License type as it was deprecated.

**Comment by ghost** [comment]
Additionally, after updating CF template to use latest OpenVPN AMI, OpenVPN fails to start up (all configuration CLI commands are failing).

**Comment by dsingh07** [comment]
Thanks @IrmantasM we have raised a defect for this internally and will proceed to fix it now

**Comment by dsingh07** [comment]
George has now fixed this in the PR: https://github.com/Accenture/adop-aws/pull/16 which will be merged once reviewed.

**Comment by marisbahtins** [comment]
PR #16 merged. AMIs now updated. Closing issue.
